### ISSUE TITLE
Enumerate all WiFi interfaces by default

### ISSUE THREAD

**Issue by jimcroft** [jcwalker/WiFiProfileManagement#13]
I've got a few machines that have default WiFi adapters not called 'Wi-Fi' which can't be renamed (no idea why).

I can put together a PR to change this modules behavior so that anytime it currently relies on defaulting to WiFiAdapterName='WiFi' it instead enumerates and uses all WiFi adapters. This would mean the exported functions would "just work" with non standard adapter names and multiple adapters without having to remember to pass the WiFiAdapterName parameter.

The https://msdn.microsoft.com/en-us/library/windows/desktop/ms706716(v=vs.85).aspx API should provide what I need.

If I put a PR together to do this would it be accepted (in principal)?

Thanks

**Comment by jcwalker** [comment]
@jimcroft this would be awesome if you were to add this functionality.  This is on my list of things to do so this is much appreciated.
